export { default as Home } from './home'
export { default as Signin } from './sign-in'
export { default as About } from './about'
export { default as Signup } from './sign-up'
export { default as Economy } from './economy'
export { default as Premium } from './premium'
export { default as Regular } from './regular'
export { default as Order } from './order'
export { default as Checkout} from './checkout'